#####################################################################
# Variables you should update for your installation
#####################################################################

# AWS region to install environment into
region: "eu-central-1"

# The public DNS for cluster, you must have a Route 53 zone configured for this
public_dns_zone: "ocpdemo.de"
# Prefix for the master, i.e. if public zone is 'ocplab.com' and the master prefix is 'master'
# then the OpenShift console will be available at 'master.ocplab.com'. If you leave this as an empty
# string it will use the public_dns_zone as the A record
prefix_master_dns: "master"
# Prefix for subdomain for wildcard DNS, i.e. *.apps.ocplab.com
public_subdomain_prefix: "apps"

# Amazon key pair to use, must exist before running script. Please generate in AWS management console.
aws_key_pair: "keypair_name"

# Specify ami you want to use, note the ami
# below refers to a gold image in ca-central-1, it's unlikely you have access
# to it so change this variable to something appropriate. Use the AWS console
# to locate a suitable image

# Standard ca-central-1 Gold Image AMI
ami_id: "ami-0e141e3c3c45456b0"

# Whether to install metrics
install_metrics: true
# Whether to install logging
install_logging: true
# Whether to enable monitoring (prometheus) storage, monitoring required
# for new console so no point not installing it
monitoring_storage_enabled: true

# Uncomment and set password for ec2-user
# which can then be used to login into cockpit. Please be
# careful and do not check this file into github. In fact
# just use the -e option when running ansible to set this
# password.
# cockpit_password: "changeme!"

# Users to create in OpenShift, highly recommend changing password
# Set admin to true for users you want to be the cluster administrator
# Any admin users are also added to master linux VM for cockpit
users:
  - {name: admin, password: password, admin: true}

# Generates a set of non-admin users that can be used for workshops,
# demos, etc. Users are created with the prefix plus a number using
# the password specified
create_generic_user: false
generic_user_prefix: roboteam
generic_user_count: 5
generic_user_password: password

#####################################################################
# SSL configuration - Optional
#####################################################################

# Option 1: Install SSL certificates for the master that you provide or
# were previously generated by Option 2
# master_ssl_cert_file: "certs/letsencrypt/ocplab.com/fullchain.pem"
# master_ssl_key_file: "certs/letsencrypt/ocplab.com/privkey.pem"
# wildcard_ssl_fullchain_file: "certs/letsencrypt/apps.ocplab.com/fullchain.pem"
# wildcard_ssl_cert_file: "certs/letsencrypt/apps.ocplab.com/fullchain.pem"
# wildcard_ssl_key_file: "certs/letsencrypt/apps.ocplab.com/privkey.pem"


# Option 2: Use let's encrypt to generate certs for master and hawkular
# note certs will be fetched to location where script is run to back
# them up and possible re-use
use_lets_encrypt: false
# e-mail address that owns the certs generated by letsencrypt
domain_email_address: "xyz@tld.com"

#####################################################################
# Variables you may optionally change for your installation
#####################################################################

# Variables for node configuration
bastion_ami_size: "t2.small"
master_ami_size: "m4.xlarge"
node_ami_size: "t2.large"
master_root_volume_size: 50
node_root_volume_size: 30
docker_volume_size: 50

# The number of application nodes in the cluster
app_nodes: 3

# Create an infra node with an elastic IP instead of combined master/infra
# Useful for larg'ish workshops where you want to split the workload and not have
# the master doing everything
standalone_infra_node: false
infra_ami_size: "m4.xlarge"
infra_root_volume_size: 50

# The type of OpenShift deployment, must be either origin or openshift-enterprise.
# To install OpenShift Enterprise, you must have a valid OpenShift subscription
# with Red Hat and provide your subscription login and pool
deployment_type: "openshift-enterprise"

# Only needed for Origin
# openshift_branch: "release-3.6"ocplab.com

# Only needed for Container Platform, note this branch does not support versions earlier then 3.11
ocp_version: "3.11"

# The network plugin use, uses the flat plugin by default
os_sdn_network_plugin_name: "redhat/openshift-ovs-subnet"
# os_sdn_network_plugin_name: "redhat/openshift-ovs-multitenant"
# os_sdn_network_plugin_name: "redhat/openshift-ovs-networkpolicy"

#####################################################################
# This playbook can optionally install CNS (Gluster) for applications.
# It will use the first three app nodes as the gluster nodes, all
# infra components requiring storage will use gluster instead of
# AWS.
#
# Also note that the AWS cloud provider will be disabled if installing
# gluster.
#
# Note some changes were made to support 3.9, this is may not be useable
# in 3.7.
#
# Note when using gluster make sure to increase the app nodes in node_ami_size
# to have 4 vCPU and 16 GB memory at a minimum, say a t2.xlarge or m4.xlarge.
#
#####################################################################
install_gluster: false
# Total storage available to OpenShift from gluster
gluster_volume_size: 300
# The block volume size, should be less then gluster_volume_size but big
# enough to host metrics and logging blocks
gluster_block_host_volume_size: 150

#####################################################################
# Variables you do not want to change unless you are sure you know
# what you are doing
#####################################################################

# metrics volume size, if using gluster and change make sure it fits in block
# volume size
metrics_volume_size: 50

# logging volume size, if using gluster and change make sure it fits in block
# volume size
logging_volume_size: 50

# Registry volume size, only used when gluster is used
registry_volume_size: 50

# Prometheus storage sizes
prometheus_volume_size: 50
alertmanager_volume_size: 2

# namespace is used to uniquely differentiate the stack through ec2 tags
namespace: "robothackathon"

# dns_zone is private zone, created and deleted by scripts
dns_zone: "ose.local"

vpc_cidr: "10.0.0.0/16"
subnet_cidr: "10.0.1.0/24"

amazon_user: "ec2-user"

# DEPRECATED: This is no longer configurable in 3.10.
htpasswd_path: "/etc/origin/master/htpasswd"

# epel repo url, needed for certbot and lets encrypt
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

pyopenssl_url: "http://cbs.centos.org/kojifiles/packages/pyOpenSSL/16.2.0/3.el7/noarch/python2-pyOpenSSL-16.2.0-3.el7.noarch.rpm"

# If true, the service catalog will be disabled
disable_service_catalog: false
