= Robot Hackathon

== Introduction

You are a special mission super coder/geek. Your mission is to complete 
several assignements using a state-of-the-art robot in a dangerous environment. 
The robot is provided by Robot Services, Ltd. Because speed is of utmost 
importance you will utilize agile and DevOps based development 
methodologies. To get productive quickly you will use the container 
platform OpenShift which will be provided by Robot Services. 

== Your Adventure starts... connect to the Robot

=== Access the API

Robot Service Ltd provides access to their robots through an API gateway based 
on the 3Scale API Management platform.

TIP: As the robots are accessed over a public API, it's important to 
restrict and limit who can use the API. The API management platform takes care 
of role-based access control, setting up accounts, monitoring, routing, traffic 
shaping and more.

Okay, let's get started. Head over to `https://rh-test.3scale.net/` and:

* Login with your team credentials (roboteam1-8, password as provided)
* After login you will see the API key you need to access the robot API

TIP: Look around in the 3Scale web UI, you will see examples of how to invoke 
the API of your robot. 3Scale will take care of routing your requests to the 
proper robot. 

WARNING: The most important information is the *Key* from the *Credentials* 
box. Using this key as *user_key* in your API calls takes care of routing the 
requests to the proper robot. 

==== Testing the API

The easiest way to test the connection to the Hub-Controller is to use the 
curl commandline under *Run your requests* from a terminal. This will test the 
connection to the Hub-Controller, *not* the robot!

----
curl https://<URI>:443/api/robot/status?user_key=<YOUR KEY>
OK 
----

==== Exploring the Robot API

There are a number of ways to test the connectivity from your PC via 3Scale to 
the robot (there are a couple of hops involved, check back to the 
architecture). You basically need to construct an URL to query the API using 
the 3Scale access token.

While in the 3Scale web UI access the *DOCUMENTATION* link in the menu bar. 
Here you will find the API documentation of all robot operation currently 
exposed in OpenAPI/Swagger format.

You can test the available API calls from here, this will actually go to your 
robot. Just remember to fill in the *USER_KEY* parameter when you test.  

=== Accessing OpenShift

Now that you can access and control your robot through the API let's get 
started with programming the robot by developing applications on our container 
platform. 

Your team user has already been created for you, the users are named 
user1-8 . Open your browser and access the OpenShift web UI:

----
https://master.berlin-4dcf.openshiftworkshop.com/console
----

* Login as your team user, e.g. *user1*, the password will be provided. 
* Look around

If you prefer the commandline *oc* tool (has to be installed on your PC), login to the OpenShift cluster is made easy by using the web UI. In the web UI click on the *?* button in the upper right and copy the 
*oc* command line. Example:

----
NN
----

Paste this into the terminal and you are good to go!


TIP: You can access OpenShift's functionalities via the web UI or a 
command line client, of course.

=== Your first application

So we are ready to start some coding. Normally you would now have to setup your 
dev environment... install IDE, language runtimes, build tool, version control 
system/access, checkout code.... etc. And most of this specific to your OS.

Because we work in a cutting edge environment we'll use CodeReady
a browser-based, cloud-native IDE running in the OpenShift environment.

Access CodeReady in your browser:

----
http://codeready-workspaces.apps.berlin-4dcf.openshiftworkshop.com
----

Click *Register* and self-register your team.

CodeReady provides development environment for several languages and runtimes. We'll 
use Java in this example for our applications.

==== Launch your workspace from CodeReady

After login you are in the Workspace management view of CodeReady. Start your 
workspace in CodeReady:

* *NAME*: team1-robot-app-workspace 
* *SELECT STACK*: Java
* Click *CREATE*
* After creation has finished a pop-up appears, click *OPEN*.

Now your CodeReady workspace should open in your browser. 

TIP: Creating a new workspace can take some time.

==== Get Application Quickstart

Robot Services Ltd has provided a basic Spring Boot-based Java application to 
quickly get you started with your first robot application. It's provided in a 
Git (Gogs) repository hosted on the OpenShift cluster. 

To get this application into your workspace:

* In your Che workspace, click *Import Project*
* In the *Import project* window:
** Choose *GIT*
** *URL*: 
\http://gitea.oapps.ose.sademo.de/<teamname>/roboapp.git
** *Name*: Adapt the name to something sensible
* In the next dialog choose *Java -> Maven*
* Click *Save*

==== Installing the OpenShift Client

To deploy application to OpenShift you need the *oc* client tool in your Che 
workspace. In the repository you just checked out is a script to download the 
client. In your Che workspace, open a terminal and run:

----
# sh /projects/robot-hackathon-<your team user>/get_oc_client.sh
----

This will download the client. 

Add it to the executable path:

----
export PATH=$PATH:/projects/ocpclient/
----

WARNING: You need to set the path again when using a new terminal: `export 
PATH=$PATH:/projects/ocpclient/`

==== Login *oc* to OpenShift from Che workspace

Before deploying applications from your Che workspace to OpenShift, you have to 
login the OpenShift client (oc) to the OpenShift environment. 

Get the login string from the OpenShift web UI:

* In the web UI, click the top right question mark, choose *Command Line Tools*
* Now a form opens, copy the *oc login...* string *using the copy button*
* Paste into the Che terminal, press *Enter*
* You should get a welcome message as you are now logged into OpenShift
* Try running `oc whoami` to make sure

=== Running the Application Locally

*Open a new terminal* in your Che workspace by clicking the *+* sign in the 
lower workspace pane. Change into your project directory:

----
cd /projects/robot-hackathon-<your team user>
----

Now build and run the application locally:

----
mvn spring-boot:run
----

WARNING: You should do this in a new terminal window because you can't stop the 
application with Ctrl-C.

Now your application should run in the embedded Tomcat server. To access the 
application web frontend, look up the URL:

* Again using the *+* sign, open a *Servers* view.
* Under *Reference* search for *Tomcat8*
* Click the URL, this will take you to the web page

By clicking the *Run* button you start the *run* method of the application. 
Using the initial check out this will print a log message you will see in the 
terminal Tomcat is running in.

=== Changing the Application

Now it's time to make the first change to the application code. The code 
structure is standard-Maven, have a look around. The log message you just 
saw is triggered in the *run()* method of class 
`../src/main/java/io/openshift/booster/service/RobotEndpoint.java`

As a first example go and change the log message and the standard output:

----
public Object run() {
        System.out.println("Hello Team");
        String response = "Hello Team";
        // Example GET invokation of the Robot API
----

Springboot will take care of recompiling and hot-swapping your code change. 
Wait until this has finished and run again by pressing *Run* on the web page.

Do this as long as you want, the goal is to get familiar with the process.

TIP: When you are finished changing code, close the terminal Tomcat is running 
in.

=== Deploying the Application to OpenShift

Until now the application runs locally in your Che workspace. To run it as a 
containerized service in OpenShift, deployable where ever you want, you have to 
build and deploy a container image from your application. And guess what? It's 
easy!

To deploy to OpenShift, run:

----
mvn clean fabric8:deploy -Popenshift -DskipTests
----

This time, the command will return because the code was deployed in a 
container/pod in OpenShift. Go to the OpenShift web console and open your 
project. You might see the build still running, after it has finished, the 
route to externally access the application will be visible in the upper right 
corner. It will look like:

----
http://hub-controller-live-<yourteamname>-project.apps-9d00.generic.opentlc.
com 
----

Clicking the route will take you to your applications web page again! But this 
time in the cloud!

Try running the *run()* method again, it should do the same as before. To see 
the log message, click the blue circle with the pod name and click on the 
*Logs* tab.

== Now the Fun Starts! 

Now you should have all the information to start hacking the robot!

=== Challenge

Task: Make your robot drive in a square with approx 20cm edge length

Hints:

* Plan what your robot should do, check the space for the square.
* Look up the API calls you need (remember the API documentation?)
* Change the code in the *run()* method (have a look at the commented out code 
examples)
* Test locally in Che if you want to
* Deploy to OpenShift

WARNING: Solution Below!

----
 MultiValueMap<String, String> paramMap = new LinkedMultiValueMap<String, 
String>();
        paramMap.add("user_key", "<API Key");
        HttpEntity<MultiValueMap<String, String>> request = new 
HttpEntity<MultiValueMap<String, String>>(paramMap,
                new LinkedMultiValueMap<String, String>());
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/forward/20", request, String.class);
        response = restTemplate.postForObject(hubControllerEndpoint + 
"/left/90", request, String.class);
----

=== Missions

* Mission 1 : Have the robot stop exactly at a certain point
* Mission 2 : Use Distance Sensor: Stop in front of the robot barrier
* Mission 3 : Navigate a predefined labyrinth
* Mission 4 : Navigate an unknown labyrinth
* Mission X : Prometheus / Grafana Dashboard (Power, Distance)














